### ISSUE TITLE
Any way to load test data into batsd over long time periods?

### ISSUE THREAD

**Issue by jjrussell** [noahhl/batsd#21]
I'm trying to test some tools built around batsd and I want to load up the database with data from a long time period quickly.  Is there a way to force data in at certain times quickly to simulate a long run of data collection? Thanks

**Comment by noahhl** [comment]
There's no "official" way to do this, but the data format of batsd is intentionally very simple, and so it should be pretty easy to generate historical data.

### For version 0.1.x:

For all datatypes in version 0.1.x, which is the current git master branch, each metric at a given aggregation level is stored in a plain text file with one line per measurement. Each line is formatted at '#{unix_timestamp} #{value}`.

Files are then stored in files named based on the MD5 hash of the metric and aggregation as `MD5(#{datatype}:#{metric}:#{aggregation}`. E.g., for the counter "foo" stored at the 60 second aggregation, it will be in `MD5(counters:foo:60)`, or `301d3485942dced564900e7f79789952`. Batsd stores files two directories deep, so that would actually be in `#{statsd_root}/30/1d/301d3485942dced564900e7f79789952`.

That file would then just contain datapoints like:

```
1356352114 34
1356352174 4
1356352234 32
1356352294 53
1356352354 28
1356352414 22
1356352474 61
1356352534 41
1356352594 56
1356352654 31
1356352714 31
```

This is the same for gauges and timers as well, with one note on timers: they're stored with a separate file for each element of them -- mean is stored in one file, min in another, max in a third, etc. In that case, their file name is `timers:#{metric}:#{operation (mean, etc.)}:#{aggregation}`.

You can use whatever mechanism you'd like to generate these files, and then it will be accessible to batsd's data server. 

### Coming in version 0.2:

Version 0.2, which is the current `dev` branch, uses a slightly different file format. We've been using this in production at 37signals for a few weeks now, and more details on this are to come (including a couple of migration paths).

For counters and gauges, there's very little changed -- still one line per datapoint, same file names. The one difference is the addition of a single line header as the first line in the file, so the above would become:

```
v2 counters:foo:60
1356352114 34
...
```

For timers, rather than write mean/min/max, etc. into separate files, they're written into a single file. Still plain text, still one row per timestamp, but now each aspect of the measurement is written to the same file, separated by a "/". Those files now look like:

```
v2 timers:random_3:60: count/min/max/median/mean/stddev/percentile_90/percentile_95/percentile_99
1355964420 4951/0/999/491/498/287/899/954/988
...
```

As you can see, we've also added median and 95th/99th percentile. This was all done for performance reasons -- we reduce the number of disk operations by 5x.

---

Hopefully that helps.
