### ISSUE TITLE
Not all incoming metrics are added to datapoints set.

### ISSUE THREAD

**Issue by bduc** [noahhl/batsd#25]
Hi,

I'm currently trying to integrate batsd into our metrics infrastructure but can't seem to get it up and running 100%.

The redis 'datapoints' set is only updated for the first metric that comes in after start of the batsd receiver, the following metrics are added into redis (I see them using redis-cli KEYS *) but the names are not added to datapoints. (SMEMBERS datapoints) 

Therefore batsd only 'exposes' a few keys to batsd-dash. 

I first tried master, then switched to dev branch on jruby using redis 2.6.12.

Were am I going wrong ?

regards

Bart

**Comment by bduc** [comment]
Please ignore my previous question for now.
I was a little too fast in questioning; datapoints are not flushed as they are received.

This issue can be closed.

**Comment by noahhl** [comment]
Sorry I missed this before. Glad you figured it out.

Delaying flushing to the `datapoints` set is, in retrospect, a relatively undesirable tradeoff -- I wanted to minimize repeatedly adding to the set unnecessarily, since most observations of a datapoint aren't new. 

In another version of batsd (github.com/noahhl/go-batsd, generally compatible w/ the dev branch of ruby batsd), I took a different approach which I tend to like -- when a file to store a datapoint is created for the first time, it adds the datapoint to the `datapoints` set. This has some delay, but much less (under a minute for most configurations), and completely eliminates unnecessary `SADD` operations. I'll try to get that backported to this repo sometime soon.
